apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapp
      version: blue
  template:
    metadata:
      labels:
        app: blogapp
        version: blue
    spec:
      containers:
      - name: blogapp
        image: 762233737972.dkr.ecr.ap-south-1.amazonaws.com/devops:24fd4d6
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: blogapp-svc
  namespace: webapps
spec:
  selector:
    app: blogapp
    version: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

