apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp
  namespace: webapps
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: blogapp
  template:
    metadata:
      labels:
        app: blogapp
    spec:
      containers:
      - name: blogapp
        image: 762233737972.dkr.ecr.ap-south-1.amazonaws.com/devops:24fd4d6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: blogapp-svc
  namespace: webapps
spec:
  selector:
    app: blogapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

