apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantapp-green
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantapp
      version: green
  template:
    metadata:
      labels:
        app: restaurantapp
        version: green
    spec:
      containers:
      - name: restaurantapp
        image: 762233737972.dkr.ecr.ap-south-1.amazonaws.com/devops:1c9d1da
        readinessProbe:
            httpGet:
              path: /blog
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /blog
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
