apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restaurantapp-ingress
  namespace: webapps
spec:
  rules:
  - host: cloud.foodenginepos.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: restaurantapp-blue-svc  # Switch to restaurantapp-green-svc for traffic shift
            port:
              number: 8080
