apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantapp-blue
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantapp
      version: blue
  template:
    metadata:
      labels:
        app: restaurantapp
        version: blue
    spec:
      containers:
      - name: restaurantapp
        image: 762233737972.dkr.ecr.ap-south-1.amazonaws.com/devops:1c9d1da
        ports:
        - containerPort: 8080